name = "HuggingFaceTokenizers"
uuid = "a6888d44-1185-43bb-bd0f-7806f9976d18"
authors = ["AntonOresten <anton.oresten42@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
